typeannonce_index:
    path:     /
    defaults: { _controller: "BricoBackBundle:TypeAnnonce:index" }
    methods:  GET

typeannonce_show:
    path:     /{id}/show
    defaults: { _controller: "BricoBackBundle:TypeAnnonce:show" }
    methods:  GET

typeannonce_new:
    path:     /new
    defaults: { _controller: "BricoBackBundle:TypeAnnonce:new" }
    methods:  [GET, POST]

typeannonce_edit:
    path:     /{id}/edit
    defaults: { _controller: "BricoBackBundle:TypeAnnonce:edit" }
    methods:  [GET, POST]

typeannonce_delete:
    path:     /{id}/delete
    defaults: { _controller: "BricoBackBundle:TypeAnnonce:delete" }
    methods:  DELETE
